workflows:
  my-workflow:
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: | 
          ./gradlew assembleRelease # -> to create the .apk

artifacts:
  - app/build/outputs/**/*.apk


